In [1]:
import numpy as np

### Simple logistic regression

$$p_i = p (y_i = 1 | x_i, w, b) = \sigma ( w x_i + b)$$

In [4]:
x = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])

$$\sigma (z) = \frac{1}{1 + e^{-z}}$$
Sigmoid -> always between 0 and 1

In [2]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

$$\theta = \begin{pmatrix} w \\ b \end{pmatrix}$$
$w$: weight\
$b$: bias

In [5]:
w = 1.2
b = -0.3

$$F_{\alpha\beta} = \mathbb{E}\left[\frac{\partial \log L}{\partial \theta_\alpha} \frac{\partial \log L}{\partial \theta_\beta} \right]$$
Or 
$$F = \sum_{i=1}^N p_i(1-p_i)\, \phi_i \phi_i^T$$

$$\phi_i = \begin{pmatrix} x_i\\ 1 \end{pmatrix}$$

In [3]:
def fisher_logistic_1d(x, w, b):
    F = np.zeros((2, 2), dtype=float)

    for xi in x:
        p = sigmoid(w * xi + b)
        weight = p * (1 - p)

        phi = np.array([xi, 1.0]).reshape(2, 1)
        F += weight * (phi @ phi.T)

    return F

$$F= \sum_{i=1}^N p_i(1-p_i) \begin{pmatrix} x_i^2 & x_i\\ x_i & 1 \end{pmatrix}$$

In [7]:
F = fisher_logistic_1d(x, w, b)
F

array([[0.97945643, 0.13272784],
       [0.13272784, 0.75530749]])

$$\mathrm{Cov} (\theta) \approx F^{-1}$$

In [8]:
cov_approx = np.linalg.inv(F)
cov_approx

array([[ 1.04588006, -0.18378926],
       [-0.18378926,  1.35626082]])

$$\Sigma = F^{-1}$$

$$\Sigma = \begin{pmatrix} \sigma_w^2 & \text{cov}(w,b) \\ \text{cov}(w,b) & \sigma_b^2 \end{pmatrix}$$

Error in $w$: $\sigma_w = \sqrt{\Sigma_{11}}$

Error en $b$: $\sigma_b = \sqrt{\Sigma_{22}}$

In [9]:
errors = np.sqrt(np.diag(cov_approx))
errors

array([1.02268278, 1.16458611])